Parameters:
  Engineer:
    Description: Name Of Engineer Who Launched Configuration
    Type: String
    Default: "Unknown"
  DBName:
    Description: Name of Database
    Type: String
    Default: WordpressDB
  DBUsername: 
    Description: Master UserName for Database
    Type: String
    Default: admin
  DBPassword:
    Description: Master Password for Database
    Type: String
  VPCCidrBlock:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
  PublicSubnetCIDR1:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/24
    Description: VPC CIDR Block for Public Subnet 1 (eg 10.0.0.0/24)
    Type: String
  PublicSubnetCIDR2:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.1.0/24
    Description: VPC CIDR Block for Public Subnet 2 (eg 10.0.1.0/24)
    Type: String
  PrivateSubnetCIDR1:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.2.0/24
    Description: VPC CIDR Block for Private Subnet 1 (eg 10.0.2.0/24)
    Type: String
  PrivateSubnetCIDR2:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.3.0/24
    Description: VPC CIDR Block for Private Subnet 2 (eg 10.0.3.0/24)
    Type: String


Resources:
  #nested stack for VPC, creates two private and two public subnets in us-east-1, uses cidr block 10.0.0.0/16
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TimeoutInMinutes: '60'  
      TemplateURL: https://wordpress-stack.s3-us-west-2.amazonaws.com/vpc.yml #replace with your own s3 hosted stack
      Parameters:
        Engineer: !Ref Engineer #reference to user entered parameter 
        VPCCidrBlock: !Ref VPCCidrBlock
        PublicSubnetCIDR1: !Ref PublicSubnetCIDR1
        PublicSubnetCIDR2: !Ref PublicSubnetCIDR2
        PrivateSubnetCIDR1: !Ref PrivateSubnetCIDR1
        PrivateSubnetCIDR2: !Ref PrivateSubnetCIDR2
  RDS: 
    #nested stack for RDS mySql Database
    Type: AWS::CloudFormation::Stack
    Properties:
      TimeoutInMinutes: '60'    
      TemplateURL: https://wordpress-stack.s3-us-west-2.amazonaws.com/rds.yml #replace with your own s3 hosted stack
      Parameters:
        PrivateSubnetID1: !GetAtt VPC.Outputs.privateSubnet1
        PrivateSubnetID2: !GetAtt VPC.Outputs.privateSubnet2
        PublicSubnetID1: !GetAtt VPC.Outputs.publicSubnet1
        PublicSubnetID2: !GetAtt VPC.Outputs.publicSubnet2
        Username: !Ref DBUsername
        Engineer: !Ref Engineer
        Password: !Ref DBPassword
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnetCIDR1: !Ref PublicSubnetCIDR1
        PublicSubnetCIDR2: !Ref PublicSubnetCIDR2
        PrivateSubnetCIDR1: !Ref PrivateSubnetCIDR1
        PrivateSubnetCIDR2: !Ref PrivateSubnetCIDR2
        VPCCidrBlock: !Ref VPCCidrBlock
        DBName: !Ref DBName
  EC2:
    #nested stack for EC2 to host the wordpress instance, contains userdata to install/launch wp and connect to mysql db
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://wordpress-stack.s3-us-west-2.amazonaws.com/ec2wordpress.yml #replace with your own s3 hosted stack
      TimeoutInMinutes: '60'
      Parameters:
        Engineer: !Ref Engineer
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBRootPassword: !Ref DBPassword
        SubnetId: !GetAtt VPC.Outputs.publicSubnet1 #public subnet to launch ec2 in for the world to access via internet gateway
        DBEndPoint: !GetAtt RDS.Outputs.DBEndpoint #access point for the db to initiate wordpress
        VPC: !GetAtt VPC.Outputs.VPC
        PrivateSubnetID1: !GetAtt VPC.Outputs.privateSubnet1
        PrivateSubnetID2: !GetAtt VPC.Outputs.privateSubnet2
        PublicSubnetCIDR1: !Ref PublicSubnetCIDR1
        PublicSubnetCIDR2: !Ref PublicSubnetCIDR2
        PrivateSubnetCIDR1: !Ref PrivateSubnetCIDR1
        PrivateSubnetCIDR2: !Ref PrivateSubnetCIDR2
        VPCCidrBlock: !Ref VPCCidrBlock
  Route53:
    #nested stack for Route 53, routes a DNS name to the ec2's public ip for web viewing
    Type: AWS::CloudFormation::Stack
    Properties:
      TimeoutInMinutes: '60'
      TemplateURL: https://wordpress-stack.s3-us-west-2.amazonaws.com/route53.yml #replace with your own s3 hosted stack
      Parameters:
        ec2PublicIP: !GetAtt EC2.Outputs.PublicIP #public ip of ec2 launched in previous stack

  

 # # 