Parameters:
    ec2PublicIP:
        Type: String

Resources:
    DNS:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: training.trambo.cloud
            Name: andreascary.training.trambo.cloud #our new web address
            ResourceRecords: !Ref ec2PublicIP
            TTL: '900'      
            Type: A